workflows:
  flutter-to-apk:
    name: Flutter Build APK
    instance_type: mac_mini_m1
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    
    triggering:
      events:
        - push
        - pull_request
    
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Build APK
        script: flutter build apk --release
    
    artifacts:
      - build/app/outputs/apk/release/app-release.apk
    
    publishing:
      email:
        recipients:
          - jafet@example.com
